const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const box={window:{},Math};vm.createContext(box);for(const name of ['shuffle','throw-gate'])vm.runInContext(fs.readFileSync(__dirname+'/../js/'+name+'.js','utf8'),box);const P=box.window.CosmicPinball;
test('all closed edges reject exits, including dragging outside then around the wall',()=>{for(const [w,h] of [[1280,720],[390,844],[844,390]])for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[-1,-1],[1,1]]){const area={w,h,s:Math.min(w-32,h-48)},g=new P.ThrowGate();g.begin(0,0,0,area);g.move(dx*g.bounds.halfWidth,dy*g.bounds.halfHeight,1000,true);assert.equal(g.takeExit(1000).fired,false);}});
test('the diagonal gap is a real opening while other walls reflect collision circles',()=>{const c=new P.HandShuffle([{id:'ball'}],'NE');c.bounds={left:-.5,right:.5,top:-.5,bottom:.5,cornerRadius:.1,opening:.18,outer:{left:-.7,right:.7,top:-.7,bottom:.7}};const b=c.bodies[0];Object.assign(b,{x:.48,y:-.48,r:.02,vx:1,vy:-1});c.wall(b);assert.equal(b.x,.48);assert.equal(b.y,-.48);assert.equal(b.vx,1);for(const [x,y,vx,vy] of [[.55,0,1,0],[0,-.55,0,-1],[-.55,0,-1,0],[0,.55,0,1]]){Object.assign(b,{x,y,vx,vy});c.wall(b);assert(b.x>=-.5+b.r-1e-8&&b.x<=.5-b.r+1e-8&&b.y>=-.5+b.r-1e-8&&b.y<=.5-b.r+1e-8);assert(b.vx*vx+b.vy*vy<=0);}});

test('outlet ends reflect incoming bodies and escaped bodies stay visible then return without reset',()=>{
 const c=new P.HandShuffle([{id:'same-ball'}],'NE-END');c.bounds={left:-.5,right:.5,top:-.5,bottom:.5,cornerRadius:.1,opening:.18,outer:{left:-.7,right:.7,top:-.7,bottom:.7}};
 const b=c.bodies[0];Object.assign(b,{x:.33,y:-.5,r:.02,vx:-1,vy:0});c.wall(b);assert(Math.hypot(b.x-.32,b.y+.5)>=b.r-1e-8);assert(b.vx>0,'wall end reflects incoming velocity');
 Object.assign(b,{x:.9,y:-.9,vx:1,vy:-1});c.wall(b);assert(b.x+b.r<=.7+1e-8&&b.y-b.r>=-.7-1e-8);const before=JSON.stringify(c.snapshot());c.release();assert.equal(JSON.stringify(c.snapshot()),before);
 for(let i=0;i<1200;i++)c.step();assert.equal(b.id,'same-ball');assert(Math.hypot(b.x,b.y)<c.clusterRadius+.05,'existing weak force returns a body that crossed the outlet');
});
